"""empty message

Revision ID: a69835464933
Revises: 05ba1c59458e
Create Date: 2022-08-01 22:58:21.861063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69835464933'
down_revision = '05ba1c59458e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('foto_url', sa.String(length=500), nullable=True))
    op.drop_column('users', 'foto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('foto', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('users', 'foto_url')
    # ### end Alembic commands ###
